vich_uploader:
    db_driver: orm

    mappings:
        fiches:
            uri_prefix: /uploads/fiches
            upload_destination: '%kernel.project_dir%/public/%app.path.fiches_images%'
        articles:
            uri_prefix: /uploads/articles
            upload_destination: '%kernel.project_dir%/public/%app.path.articles_images%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
